### ISSUE TITLE
User Groups within Handler?

### ISSUE THREAD

**Issue by Skarzee** [knuedge/lita-puppet#13]
Hey guys, 

Great plugin and found good success so far to encourage transparency within my current workplace. Also cert removals generally suck.
 
One thing that I have wondered however is whether or not there should be a mandatory group created to allow access to this handler. An example of which can be found with something like the [lita-marathon](https://github.com/silvamerica/lita-marathon) plugin which we also use.

I am not sure how you are running it yourselves, but a whole organisation having access to the plugin might not be for the best. Due to the inbuilt authentication system, this could be created and managed easily.

Happy to collaborate on a PR if you agree there is a need, even if that is in the form of documentation that details how to do so.

**Comment by jgnagy** [comment]
Great suggestion. In our case, we bind purpose-built chatbots to private rooms / channels. We preferred that approach as it makes it much more obvious who has access, and we only need to change one place (our IM service). That said, this is definitely something we can work on as an additional feature, and we'll make it optional just so it doesn't break anyone already using it.

PRs are always welcome; just make sure the tests still pass (and write tests for new features).

**Comment by Skarzee** [comment]
Thanks for getting back to me on this one, and I'm glad you think it could be a worthwhile feature. I'll looking into implementing this as an addition perhaps where you can specify the group that you want to add it to (meaning that you can implement it to groups that already exist). 

I'll have a look at this next week, and throw in an initial PR, but I might need a little assistance with the testing aspects.

**Comment by Skarzee** [comment]
Closure due feature enhancement with to #14. Good stuff @dschaaff !
